# Generated by Django 5.1.5 on 2025-12-18 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_habitacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitacion',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='habitacion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='generar_habitaciones_auto',
        ),
    ]
