# Generated by Django 5.1.5 on 2025-12-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_habitacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitacion',
            options={'ordering': ['numero']},
        ),
        migrations.AddField(
            model_name='hotel',
            name='generar_habitaciones_auto',
            field=models.BooleanField(default=True, verbose_name='Generar habitaciones automáticamente'),
        ),
        migrations.AlterUniqueTogether(
            name='habitacion',
            unique_together={('hotel', 'numero')},
        ),
    ]
