# Generated by Django 5.1.5 on 2025-12-18 06:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_habitacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitacion',
            options={'ordering': ['hotel', 'numero'], 'verbose_name': 'Habitación', 'verbose_name_plural': 'Habitaciones'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['nombre'], 'verbose_name': 'Hotel', 'verbose_name_plural': 'Hoteles'},
        ),
        migrations.AlterModelOptions(
            name='huesped',
            options={'ordering': ['nombre'], 'verbose_name': 'Huésped', 'verbose_name_plural': 'Huéspedes'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_reserva', '-fecha_creacion'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='notas_admin',
            field=models.TextField(blank=True, verbose_name='Notas del administrador'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='foto',
            field=models.ImageField(blank=True, default='hoteles/default.jpg', upload_to='hoteles/'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('rechazada', 'Rechazada'), ('completada', 'Completada')], default='pendiente', max_length=10),
        ),
    ]
